# Generated by Django 4.1.5 on 2023-03-13 02:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='path',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
