# Generated by Django 4.1.5 on 2023-03-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_like_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='path_length',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
