# Generated by Django 4.1.5 on 2023-05-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_category_path_remove_category_path_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='describe',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
