# Generated by Django 4.1.5 on 2023-05-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
